version: 0.2

env:
  parameter-store:
    TWINE_USERNAME: /CodeBuild/pypi-user
    TWINE_PASSWORD: /CodeBuild/pypi-password
    GITHUB_TOKEN: /CodeBuild/GITHUB_TOKEN
  variables:
    CODE_VERSION: 0.1

phases:
  build:
    commands:
      - pip install --upgrade setuptools wheel twine
      - mkdir -p tmp
      - cp -r LICENCE.txt setup.py README.md release.sh sceptre_dot tmp/
      - cd tmp && ./release.sh
